# Generated by Django 5.2.13 on 2026-05-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('trainer', 'Trainer'), ('student', 'Student')], max_length=10),
        ),
    ]
