# Generated by Django 5.2.13 on 2026-06-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_usersettings_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
