# Generated by Django 6.0.3 on 2026-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_timestamp_locationlog_tracked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
