"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.2.13.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# Load environment variables
load_dotenv(PROJECT_ROOT / '.env')


# SECURITY
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-vz5&_)17wlbwn3##qv@_m)w9(#0uub-q+lq)no3mieg)irp3x^')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')


# APPLICATIONS
INSTALLED_APPS = [
    'jazzmin',
]
if not DEBUG:
    INSTALLED_APPS.append('daphne')
INSTALLED_APPS += [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Custom apps
    'accounts',
    'dashboard',
    'captcha',
    'courses',
    'assignments',
    'progress',
    'notifications',
    'enrollments',
    'teams',
    'attendance',
    'ai_chat',
    'settings',
    'certificates',
    'coding_tasks',
]
if DEBUG:
    INSTALLED_APPS.append('channels')

# WhiteNoise for production
if not DEBUG:
    INSTALLED_APPS.insert(6, 'whitenoise.runserver_nostatic')

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# django-allauth settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
LOGIN_REDIRECT_URL = '/attendance/student/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'

# Custom adapters
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

# Social account providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}



from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'

USE_I18N = True

LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
    ('te', 'Telugu'),
    ('kn', 'Kannada'),
    ('ml', 'Malayalam'),
    ('ur', 'Urdu'),
    ('ta', 'Tamil'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # IMPORTANT FOR LANGUAGE SWITCH
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # django-allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

# WhiteNoise middleware for production
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# ROOT URL
ROOT_URLCONF = 'lms.urls'

# RAZORPAY SETTINGS 💳
# -----------------------
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_SlwV9Vy26UoaY6')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'VKNQeiPnBuL82ZCdrrnnYVq7')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')

# # IMPORTANT for prod
# DEBUG = False
# ALLOWED_HOSTS = ["E-learing.com"]

# CSRF_TRUSTED_ORIGINS = ["https://E-learing.com"]

# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_ROOT / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI
WSGI_APPLICATION = 'lms.wsgi.application'
ASGI_APPLICATION = "lms.asgi.application"
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'AIzaSyA8j5dfLgPnJZygG-Urlo5gMWrOEm6WedE')

# DATABASE
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# STATIC FILES
STATIC_URL = '/static/'
STATIC_ROOT = PROJECT_ROOT / 'staticfiles'

STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, 'frontend', 'static'),
]

# WhiteNoise compression and caching for production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# MEDIA FILES
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# DEFAULT PRIMARY KEY
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# AUTHENTICATION REDIRECTS ✅ IMPORTANT FIX
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/attendance/student/'
LOGOUT_REDIRECT_URL = '/login/'

# -----------------------
# EMAIL SETTINGS (for OTP)
# -----------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mahibanavath979@gmail.com' # Updated with actual Gmail address
EMAIL_HOST_PASSWORD = 'txlg yyed uvxi scvg' # Replace with your generated App Password
